const State = {
    AK: "Alaska", 
    AL: "Alabama", 
    AR: "Arkansas", 
    AZ: "Arizona", 
    CA: "California", 
    CO: "Colorado", 
    CT: "Connecticut", 
    DE: "Delaware", 
    FL: "Florida", 
    GA: "Georgia", 
    HI: "Hawaii", 
    IA: "Iowa", 
    ID: "Idaho", 
    IL: "Illinois", 
    IN: "Indiana", 
    KS: "Kansas", 
    KY: "Kentucky", 
    LA: "Louisiana", 
    MA: "Massachusetts", 
    MD: "Maryland", 
    ME: "Maine", 
    MI: "Michigan", 
    MN: "Minnesota", 
    MO: "Missouri", 
    MS: "Mississippi", 
    MT: "Montana", 
    NC: "North Carolina", 
    ND: "North Dakota", 
    NE: "Nebraska", 
    NH: "New Hampshire", 
    NJ: "New Jersey", 
    NM: "New Mexico", 
    NV: "Nevada", 
    NY: "New York", 
    OH: "Ohio", 
    OK: "Oklahoma", 
    OR: "Oregon", 
    PA: "Pennsylvania", 
    RI: "Rhode Island", 
    SC: "South Carolina", 
    SD: "South Dakota", 
    TN: "Tennessee", 
    TX: "Texas", 
    UT: "Utah", 
    VA: "Virginia", 
    VT: "Vermont", 
    WA: "Washington", 
    WI: "Wisconsin", 
    WV: "West Virginia", 
    WY: "Wyoming"
};

const DeathCause = {
    1: "Not Service Related",
    2: "Killed in Action",
    3: "Killed in Wartime Accident or Crash",
    4: "Died Of Wounds",
    5: "Wounded in Action",
    6: "Died Of Wartime Illness",
    7: "Missing in Action",
    8: "Lost At Sea",
    9: "Service Disabled Veteran"
}

const SeparationType = {
    1: "Honorable Discharge",
    2: "General Discharge Under Honorable Conditions",
    3: "Entry-level Separation",
    4: "Medical Separation",
    5: "Separation for Convenience of the Government",
    6: "Other"
}

const BurialPlace = {
    1: "Alabama National Cemetery",
    2: "Fort McClellan Post Cemetery",
    3: "Fort McClellan EPW Cemetery",
    4: "Fort Mitchell National Cemetery",
    5: "Mobile National Cemetery",
    6: "Fort Richardson National Cemetery",
    7: "Sitka National Cemetery",
    8: "National Memorial Cemetery of Arizona",
    9: "Prescott National Cemetery",
    10: "Fayetteville National Cemetery",
    11: "Fort Smith National Cemetery",
    12: "Little Rock National Cemetery",
    13: "Bakersfield National Cemetery",
    14: "Benicia Arsenal Post Cemetery",
    15: "Fort Rosecrans National Cemetery",
    16: "Golden Gate National Cemetery",
    17: "Los Angeles National Cemetery",
    18: "Miramar National Cemetery",
    19: "Riverside National Cemetery",
    20: "Sacramento Valley National Cemetery",
    21: "San Joaquin Valley National Cemetery",
    22: "Fort Logan National Cemetery",
    23: "Fort Lyon National Cemetery",
    24: "Pikes Peak National Cemetery",
    25: "Congressional Cemetery Government Lots",
    26: "Barrancas National Cemetery",
    27: "Bay Pines National Cemetery",
    28: "Cape Canaveral National Cemetery",
    29: "Florida National Cemetery",
    30: "Jacksonville National Cemetery",
    31: "Sarasota National Cemetery",
    32: "South Florida National Cemetery",
    33: "St. Augustine National Cemetery",
    34: "Tallahassee National Cemetery",
    35: "Georgia National Cemetery",
    36: "Marietta National Cemetery",
    37: "National Memorial Cemetery of the Pacific",
    38: "Snake River Canyon National Cemetery",
    39: "Abraham Lincoln National Cemetery",
    40: "Alton National Cemetery",
    41: "Camp Butler National Cemetery",
    42: "Danville National Cemetery",
    43: "Fort Sheridan National Cemetery",
    44: "Mound City National Cemetery",
    45: "Quincy National Cemetery",
    46: "Rock Island National Cemetery",
    47: "Confederate Mound",
    48: "North Alton Confederate Cemetery",
    49: "Rock Island Confederate Cemetery",
    50: "Crown Hill National Cemetery",
    51: "Marion National Cemetery",
    52: "New Albany National Cemetery",
    53: "Crown Hill Cemetery Confederate Plot",
    54: "Woodlawn Monument Site",
    55: "Keokuk National Cemetery",
    56: "Oakdale Cemetery Soldiers' Lot",
    57: "Fort Leavenworth National Cemetery",
    58: "Fort Scott National Cemetery",
    59: "Baxter Springs City Soldiers' Lot",
    60: "Mound City Cemetery Soldiers' Lot",
    61: "Camp Nelson National Cemetery",
    62: "Cave Hill National Cemetery",
    63: "Lebanon National Cemetery",
    64: "Lexington National Cemetery",
    65: "Mill Springs National Cemetery",
    66: "Zachary Taylor National Cemetery",
    67: "Evergreen Cemetery Soldiers' Lot",
    68: "Alexandria National Cemetery",
    69: "Baton Rouge National Cemetery",
    70: "Louisiana National Cemetery",
    71: "Port Hudson National Cemetery",
    72: "Acadia National Cemetery",
    73: "Togus National Cemetery",
    74: "Mount Pleasant Cemetery Soldiers' Lot",
    75: "Annapolis National Cemetery",
    76: "Baltimore National Cemetery",
    77: "Loudon Park National Cemetery",
    78: "Point Lookout Confederate Cemetery",
    79: "Fort Devens Post Cemetery",
    80: "Massachusetts National Cemetery",
    81: "Woodlawn Cemetery Soldiers' Lot",
    82: "Great Lakes National Cemetery",
    83: "Fort Mackinac Post Cemetery",
    84: "Lakeside Cemetery Soldiers' Lot",
    85: "Fort Snelling National Cemetery",
    86: "Biloxi National Cemetery",
    87: "Corinth National Cemetery",
    88: "Natchez National Cemetery",
    89: "Jefferson Barracks National Cemetery",
    90: "Jefferson City National Cemetery",
    91: "Springfield National Cemetery",
    92: "Union Confederate Monument Site",
    93: "Fort Missoula Post Cemetery",
    94: "Yellowstone National Cemetery",
    95: "Fort McPherson National Cemetery",
    96: "Omaha National Cemetery",
    97: "Forest Lawn Cemetery Soldiers' Lot",
    98: "Beverly National Cemetery",
    99: "Finn's Point National Cemetery",
    100: "Fort Bayard National Cemetery",
    101: "Santa Fe National Cemetery",
    102: "Bath National Cemetery",
    103: "Calverton National Cemetery",
    104: "Cypress Hills National Cemetery",
    105: "Gerald B. H. Solomon Saratoga National Cemetery",
    106: "Long Island National Cemetery",
    107: "Western New York National Cemetery",
    108: "Woodlawn National Cemetery",
    109: "Albany Rural Cemetery Soldiers' Lot",
    110: "New Bern National Cemetery",
    111: "Raleigh National Cemetery",
    112: "Salisbury National Cemetery",
    113: "Wilmington National Cemetery",
    114: "Fargo National Cemetery",
    115: "Dayton National Cemetery",
    116: "Ohio Western Reserve National Cemetery",
    117: "Camp Chase Confederate Cemetery",
    118: "Confederate Stockade Cemetery",
    119: "Woodland Cemetery Soldiers' Lot",
    120: "Fort Gibson National Cemetery",
    121: "Fort Sill National Cemetery",
    122: "Eagle Point National Cemetery",
    123: "Fort Stevens National Cemetery",
    124: "Roseburg National Cemetery",
    125: "Willamette National Cemetery",
    126: "Indiantown Gap National Cemetery",
    127: "National Cemetery of the Alleghenies",
    128: "Philadelphia National Cemetery",
    129: "Washington Crossing National Cemetery",
    130: "Allegheny Cemetery Soldiers' Lot",
    131: "Ashland Cemetery Soldiers' Lot",
    132: "Mount Moriah Cemetery Soldiers' Lot",
    133: "Mount Moriah Cemetery Naval Plot",
    134: "Prospect Hill Cemetery Soldiers' Lot",
    135: "Puerto Rico National Cemetery",
    136: "Morovis National Cemetery",
    137: "Beaufort National Cemetery",
    138: "Florence National Cemetery",
    139: "Fort Jackson National Cemetery",
    140: "Black Hills National Cemetery",
    141: "Fort Meade National Cemetery",
    142: "Hot Springs National Cemetery",
    143: "Chattanooga National Cemetery",
    144: "Memphis National Cemetery",
    145: "Mountain Home National Cemetery",
    146: "Nashville National Cemetery",
    147: "Dallas-Fort Worth National Cemetery",
    148: "Fort Bliss National Cemetery",
    149: "Fort Sam Houston National Cemetery",
    150: "Houston National Cemetery",
    151: "San Antonio National Cemetery",
    152: "Fort Douglas Post Cemetery",
    153: "Green Mount Cemetery Soldiers' Lot",
    154: "Ball's Bluff National Cemetery",
    155: "City Point National Cemetery",
    156: "Cold Harbor National Cemetery",
    157: "Culpeper National Cemetery",
    158: "Fort Harrison National Cemetery",
    159: "Glendale National Cemetery",
    160: "Hampton National Cemetery",
    161: "Hampton National Cemetery (VAMC)",
    162: "Quantico National Cemetery",
    163: "Richmond National Cemetery",
    164: "Staunton National Cemetery",
    165: "Winchester National Cemetery",
    166: "Fort Lawton Post Cemetery",
    167: "Fort Worden Post Cemetery",
    168: "Tahoma National Cemetery",
    169: "Vancouver Barracks National Cemetery",
    170: "Grafton National Cemetery",
    171: "West Virginia National Cemetery",
    172: "Northwoods National Cemetery",
    173: "Wood National Cemetery",
    174: "Fort Winnebago Cemetery Soldiers' Lot",
    175: "Forest Hill Cemetery Soldiers' Lot",
    176: "Forest Home Cemetery Soldiers' Lot",
    177: "Fort Crawford Cemetery Soldiers' Lot",
    178: "Mound Cemetery Soldiers' Lot",
    179: "Cheyenne National Cemetery" 
}

const Relationship = {
    1: "This is my Veteran profile",
    2: "Husband",
    3: "Wife",
    4: "Son",
    5: "Daughter",
    6: "Father",
    7: "Mother",
    8: "Brother",
    9: "Sister",
    10: "Father-in-law",
    11: "Mother-in-law",
    12: "Sister-in-law",
    13: "Brother-in-law",
    14: "Uncle",
    15: "Aunt",
    16: "Cousin",
    17: "Niece",
    18: "Nephew",
    19: "Grandmother",
    20: "Grandfather",
    21: "Great Grandfather",
    22: "Great Grandmother",
    23: "Fellow Military",
    24: "Friend",
    25: "Anonymous"
}

const ServiceBranch = {
    1: "Air Force",
    2: "Army",
    3: "Coast Guard",
    4: "Marine Corps",
    5: "Navy",
    6: "Space Force"
}

const RankByBranch = {
    1: {
        1: 'Airman',
        2: 'Airman Basic',
        3: 'Airman First Class',
        4: 'Brigadier General',
        5: 'Captain',
        6: 'Chief Master Sergeant',
        7: 'Chief Master Sergeant of the Air Force',
        8: 'Colonel',
        9: 'Command Chief Master Sergeant',
        10: 'First Lieutenant',
        11: 'General',
        12: 'General of the Air Force',
        13: 'Lieutenant Colonel',
        14: 'Lieutenant General',
        15: 'Major',
        16: 'Major General',
        17: 'Master Sergeant',
        18: 'Second Lieutenant',
        19: 'Senior Airman',
        20: 'Senior Enlisted Advisor to the Chairman',
        21: 'Senior Enlisted Advisor to the Chief of the National Guard Bureau',
        22: 'Senior Master Sergeant',
        23: 'Staff Sergeant',
        24: 'Technical Sergeant'
    },
    2: {
        25: 'Brigadier General',
        26: 'Captain',
        27: 'Chief Warrant Officer 2',
        28: 'Chief Warrant Officer 3',
        29: 'Chief Warrant Officer 4',
        30: 'Chief Warrant Officer 5',
        31: 'Colonel',
        32: 'Command Sergeant Major',
        33: 'Corporal',
        34: 'First Lieutenant',
        35: 'First Sergeant',
        36: 'General',
        37: 'General of the Army',
        38: 'Lieutenant Colonel',
        39: 'Lieutenant General',
        40: 'Major',
        41: 'Major General',
        42: 'Master Sergeant',
        43: 'Private',
        44: 'Private',
        45: 'Private First Class',
        46: 'Second Lieutenant',
        47: 'Senior Enlisted Advisor to the Chairman',
        48: 'Sergeant',
        49: 'Sergeant First Class',
        50: 'Sergeant Major',
        51: 'Sergeant Major of the Army',
        52: 'Specialist',
        53: 'Staff Sergeant',
        54: 'Warrant Officer 1'
    },
    3: {
        55: 'Admiral',
        56: 'Captain',
        57: 'Chief Petty Officer',
        58: 'Chief Warrant Officer 2',
        59: 'Chief Warrant Officer 3',
        60: 'Chief Warrant Officer 4',
        61: 'Command Master Chief Petty Officer',
        62: 'Commander',
        63: 'Deputy Master Chief Petty Officer of the Coast Guard',
        64: 'Ensign',
        65: 'Lieutenant',
        66: 'Lieutenant (Junior Grade)',
        67: 'Lieutenant Commander',
        68: 'Master Chief Petty Officer',
        69: 'Master Chief Petty Officer of the Coast Guard',
        70: 'Petty Officer First Class',
        71: 'Petty Officer Second Class',
        72: 'Petty Officer Third Class',
        73: 'Rear Admiral',
        74: 'Rear Admiral (Lower Half)',
        75: 'Seaman',
        76: 'Seaman Apprentice',
        77: 'Seaman Recruit',
        78: 'Senior Chief Petty Officer',
        79: 'Vice Admiral'
    },
    4: {
        80: 'Brigadier General',
        81: 'Captain',
        82: 'Chief Warrant Officer 2',
        83: 'Chief Warrant Officer 3',
        84: 'Chief Warrant Officer 4',
        85: 'Chief Warrant Officer 5',
        86: 'Colonel',
        87: 'Corporal',
        88: 'First Lieutenant',
        89: 'First Sergeant',
        90: 'General',
        91: 'Gunnery Sergeant',
        92: 'Lance Corporal',
        93: 'Lieutenant Colonel',
        94: 'Lieutenant General',
        95: 'Major',
        96: 'Major General',
        97: 'Marine Gunner',
        98: 'Master Gunnery Sergeant',
        99: 'Master Sergeant',
        100: 'Private',
        101: 'Private First Class',
        102: 'Second Lieutenant',
        103: 'Senior Enlisted Advisor to the Chairman',
        104: 'Sergeant',
        105: 'Sergeant Major',
        106: 'Sergeant Major of the Marine Corps',
        107: 'Staff Sergeant',
        108: 'Warrant Officer 1'
    },
    5: {
        109: 'Admiral',
        110: 'Captain',
        111: 'Chief Petty Officer',
        112: 'Chief Warrant Officer 2',
        113: 'Chief Warrant Officer 3',
        114: 'Chief Warrant Officer 4',
        115: 'Chief Warrant Officer 5',
        116: 'Command Master Chief Petty Officer',
        117: 'Command Senior Chief Petty Officer',
        118: 'Commander',
        119: 'Ensign',
        120: 'Fleet Admiral',
        121: 'Fleet/Force Master Chief Petty Officer',
        122: 'Lieutenant',
        123: 'Lieutenant (Junior Grade)',
        124: 'Lieutenant Commander',
        125: 'Master Chief Petty Officer',
        126: 'Master Chief Petty Officer of the Navy',
        127: 'Petty Officer First Class',
        128: 'Petty Officer Second Class',
        129: 'Petty Officer Third Class',
        130: 'Rear Admiral',
        131: 'Rear Admiral (Lower Half)',
        132: 'Seaman',
        133: 'Seaman Apprentice',
        134: 'Seaman Recruit',
        135: 'Senior Chief Petty Officer',
        136: 'Senior Enlisted Advisor to the Chairman',
        137: 'Vice Admiral',
        138: 'Warrant Officer 1'
    },
    6: {
        139: 'Brigadier General',
        140: 'Cadet / Officer Trainee',
        141: 'Captain',
        142: 'Chief Master Sergeant',
        143: 'Chief Master Sergeant of the Space Force',
        144: 'Colonel',
        145: 'First Lieutenant',
        146: 'General',
        147: 'Lieutenant Colonel',
        148: 'Lieutenant General',
        149: 'Major',
        150: 'Major General',
        151: 'Master Sergeant',
        152: 'Second Lieutenant',
        153: 'Senior Enlisted Advisor to the Chairman',
        154: 'Senior Master Sergeant',
        155: 'Sergeant',
        156: 'Specialist 1',
        157: 'Specialist 2',
        158: 'Specialist 3',
        159: 'Specialist 4',
        160: 'Technical Sergeant'
    }
}

const Badges = {
	1: 'Aerial Achievement Medal',
	2: 'Aeronautical Merit Cross (Peru)',
	3: 'Afghanistan Campaign Medal',
	4: 'Air and Space Campaign Medal',
	5: 'Air Force Achievement Medal',
	6: 'Air Force Basic Military Training Honor Graduate Ribbon',
	7: 'Air Force Combat Action Medal',
	8: 'Air Force Combat Readiness Medal',
	9: 'Air Force Commendation Medal',
	10: 'Air Force Cross',
	11: 'Air Force Distinguished Service Medal',
	12: 'Air Force Expeditionary Service Ribbon',
	13: 'Air Force Gallant Unit Citation',
	14: 'Air Force Good Conduct Medal',
	15: 'Air Force Longevity Service Award',
	16: 'Air Force Meritorious Unit Award',
	17: 'Air Force Military Training Instructor Ribbon',
	18: 'Air Force NCO PME Graduate Ribbon',
	19: 'Air Force Organizational Excellence Award',
	20: 'Air Force Outstanding Unit Award',
	21: 'Air Force Overseas Long Tour Service Ribbon',
	22: 'Air Force Overseas Short Tour Service Ribbon',
	23: 'Air Force Presidential Unit Citation',
	24: 'Air Force Recognition Ribbon',
	25: 'Air Force Recruiter Ribbon',
	26: 'Air Force Small Arms Expert Marksmanship Ribbon',
	27: 'Air Force Special Duty Ribbon',
	28: 'Air Force Training Ribbon',
	29: 'Air Medal',
	30: 'Air Reserve Forces Meritorious Service Medal',
	31: 'Airmanâ€™s Medal',
	32: 'American Campaign Medal',
	33: 'American Defense Service Medal',
	34: 'Antarctica Service Medal',
	35: 'Armed Forces Expeditionary Medal',
	36: 'Armed Forces Reserve Medal',
	37: 'Armed Forces Service Medal',
	38: 'Army Achievement Medal',
	39: 'Army Commendation Medal',
	40: 'Army Distinguished Service Cross',
	41: 'Army Distinguished Service Medal',
	42: 'Army Good Conduct Medal',
	43: 'Army Meritorious Unit Commendation',
	44: 'Army NCO Professional Development Ribbon',
	45: 'Army of Cuban Occupation Medal',
	46: 'Army of Occupation Medal',
	47: 'Army of Occupation of Germany Medal',
	48: 'Army of Puerto Rican Occupation Medal',
	49: 'Army Overseas Service Ribbon',
	50: 'Army Presidential Unit Citation',
	51: 'Army Reserve Components Achievement Medal',
	52: 'Army Reserve Overseas Training Ribbon',
	53: 'Army Sea Duty Ribbon',
	54: 'Army Service Ribbon',
	55: 'Army Superior Unit Award',
	56: 'Army Valorous Unit Award',
	57: 'Army Wound Ribbon',
	58: 'Asiatic Pacific Campaign Medal',
	59: 'Battle of Manila Bay Medal (Dewey Medal)',
	60: 'Belgian Croix de guerre (1944)',
	61: 'Belgian Croix de guerre (WW1)',
	62: 'British Order of the Bath',
	63: 'Bronze Star Medal',
	64: 'Butler Medal',
	65: 'Byrd Antarctic Expedition Medal',
	66: 'Cardenas Medal of Honor',
	67: 'Certificate of Merit Medal',
	68: 'China Campaign Medal (Army)',
	69: 'China Reflief Expedition Medal (Navy)',
	70: 'China Service Medal',
	71: 'Civil War Campaign Medal',
	72: 'Coast Guard ""E"" Ribbon',
	73: 'Coast Guard Achievement Medal',
	74: 'Coast Guard Arctic Service Medal',
	75: 'Coast Guard Basic Training Honor Graduate Ribbon',
	76: 'Coast Guard Bicentennial Unit Commendation',
	77: 'Coast Guard Bronze Pistol Excellence-in-Competition Award',
	78: 'Coast Guard Bronze Rifle Excellence-in-Competition Award',
	79: 'Coast Guard Combat Action Ribbon',
	80: 'Coast Guard Commendation Medal',
	81: 'Coast Guard Cross',
	82: 'Coast Guard Distinguished Marksman Award',
	83: 'Coast Guard Distinguished Pistol Shot Award',
	84: 'Coast Guard Distinguished Service Medal',
	85: 'Coast Guard Enlisted Person of the Year Ribbon',
	86: 'Coast Guard Expert Pistol Shot Medal',
	87: 'Coast Guard Expert Rifleman Medal',
	88: 'Coast Guard Good Conduct Medal',
	89: 'Coast Guard Medal',
	90: 'Coast Guard Meritorious Team Commedation',
	91: 'Coast Guard Meritorious Unit Commendation',
	92: 'Coast Guard Overseas Service Ribbon',
	93: 'Coast Guard Pistol Marksmanship Ribbon',
	94: 'Coast Guard Pistol Marksmanship Ribbon with Sharpshooter Device',
	95: 'Coast Guard Presidential Unit Citation',
	96: 'Coast Guard Recruiting Service Ribbon',
	97: 'Coast Guard Reserve Good Conduct Medal',
	98: 'Coast Guard Restricted Duty Ribbon',
	99: 'Coast Guard Rifle Marksmanship Ribbon',
	100: 'Coast Guard Rifle Marksmanship Ribbon with Sharpshooter Device',
	101: 'Coast Guard Sea Service Ribbon',
	102: 'Coast Guard Silver Pistol Excellence-in-Competition Award',
	103: 'Coast Guard Silver Rifle Excellence-in-Competition Award',
	104: 'Coast Guard Special Operations Service Ribbon',
	105: 'Coast Guard Unit Commendation',
	106: 'Cold War Victory Medal',
	107: 'Commandantâ€™s Letter of Commendation',
	108: 'Cross of Honor (Germany)',
	109: 'Cuban Pacification Medal (Army)',
	110: 'Czechoslovak War Cross (1918)',
	111: 'Czechoslovak War Cross (1945)',
	112: 'Defense Distinguished Service Medal',
	113: 'Defense Meritorious Service Medal',
	114: 'Defense Superior Service Medal',
	115: 'DHS Outstanding Unit Award',
	116: 'Distinguished Flying Cross Ribbon',
	117: 'Distinguished Warfare Medal',
	118: 'Dominican Campaign Medal (1916)',
	119: 'European-African-Middle Eastern Campaign Medal',
	120: 'Fleet Marine Force Ribbon',
	121: 'Four Chaplainsâ€™ Medal',
	122: 'French Croix de guerre (1914-1918)',
	123: 'French Croix de guerre (1939-1945)',
	124: 'French Legion of Honor',
	125: 'French Military Medal',
	126: 'Global War on Terrorism Expeditionary Medal',
	127: 'Global War on Terrorism Service Medal',
	128: 'Haitian Campgain Medal (1915 & 1920-1921)',
	129: 'Homeland Security Distinguished Service Medal',
	130: 'Humanitarian Service Medal',
	131: 'Indian Campaign Medal',
	132: 'Inherent Resolve Campaign Medal',
	133: 'Inter-American Defense Board Medal',
	134: 'Iraq Campaign Medal',
	135: 'Joint Meritorious Unit Award',
	136: 'Joint Service Achievement Medal',
	137: 'Joint Service Commendation Medal',
	138: 'Khalifiyyeh Order of Bahrain',
	139: 'Korea Defense Service Medal',
	140: 'Korean Service Medal',
	141: 'Kosovo Campaign Medal',
	142: 'Kuwait Liberation Medal (Kuwait)',
	143: 'Kuwait Liberation Medal (Saudi Arabia)',
	144: 'Legion of Merit',
	145: 'Luxembourg War Cross',
	146: 'Luxembourg War Cross (Unit Citation)',
	147: 'Marine Corps Brevet Medal',
	148: 'Marine Corps Combat Instructor Ribbon',
	149: 'Marine Corps Drill Instructor Ribbon',
	150: 'Marine Corps Expeditionary Medal',
	151: 'Marine Corps Good Conduct Medal',
	152: 'Marine Corps Recruiting Ribbon',
	153: 'Marine Corps Reserve Ribbon',
	154: 'Marine Corps Security Guard Ribbon',
	155: 'Medal for Humane Action',
	156: 'Medal of Honor',
	157: 'Medal of Merit (Nicaragua)',
	158: 'Meritorious Service Medal',
	159: 'Mexian Border Service Medal',
	160: 'Mexican Service Medal (1911-1917)',
	161: 'Military Merit Medal (Haiti)',
	162: 'Military Merit Order (United Arab Emirates)',
	163: 'Multinational Force and Observers Medal',
	164: 'National Defense Service Medal',
	165: 'NATO Medal (Kosovo)',
	166: 'NATO Medal (Non-Article 5)',
	167: 'NATO Medal (Yugoslavia)',
	168: 'Naval Reserve Medal',
	169: 'Naval Reserve Meritorious Service Medal',
	170: 'Naval Reserve Sea Service Ribbon',
	171: 'Navy ""E"" Ribbon',
	172: 'Navy Accession Training Service Ribbon',
	173: 'Navy and Marine Corps Achievement Medal',
	174: 'Navy and Marine Corps Commendation Medal',
	175: 'Navy and Marine Corps Medal',
	176: 'Navy and Marine Corps Overseas Service Ribbon',
	177: 'Navy and Marine Corps Presidential Unit Citation',
	178: 'Navy Arctic Service Ribbon',
	179: 'Navy Basic Military Training Honor Graduate Ribon',
	180: 'Navy Ceremonial Guard Ribbon',
	181: 'Navy Combat Action Ribbon',
	182: 'Navy Cross Ribbon',
	183: 'Navy Distinguished Marksman and Pistol Shot Ribbon',
	184: 'Navy Distinguished Marksman Ribbon',
	185: 'Navy Distinguished Pistol Shot Ribbon',
	186: 'Navy Distinguished Service Medal',
	187: 'Navy Expeditionary Medal',
	188: 'Navy Expert Pistol Shot Medal',
	189: 'Navy Expert Rifleman Medal',
	190: 'Navy Good Conduct Medal',
	191: 'Navy Meritorious Unit Commendation',
	192: 'Navy Pistol Marksmanship Ribbon',
	193: 'Navy Pistol Marksmanship Ribbon with Sharpshooter Device',
	194: 'Navy Recruiting Service Ribbon',
	195: 'Navy Rifle Marksmanship Ribbon',
	196: 'Navy Rifle Marksmanship Ribbon with Sharpshooter Device',
	197: 'Navy Sea Service Deployment Ribbon',
	198: 'Navy Unit Commendation',
	199: 'NC-4 Medal',
	200: 'Nicaraguan Campaign Medal (1912)',
	201: 'Nicaraguan Campaign Medal (1926-1930)',
	202: 'Nuclear Deterrence Operations Service Medal',
	203: 'Order of Abdon CalderÃ³n (Ecuador)',
	204: 'Order of Adolphe of Nassau (Luxembourg)',
	205: 'Order of Leopold (Belgium)',
	206: 'Order of May (Argentina)',
	207: 'Order of Merit (Germany)',
	208: 'Order of Merit of the Italian Republic',
	209: 'Order of National Security Merit (Korea)',
	210: 'Order of Orange-Nassau (Netherlands)',
	211: 'Order of Ouissam Alaouite (Morocco)',
	212: 'Order of Pao Ting (China)',
	213: 'Order of the Aztec Eagle',
	214: 'Order of the British Empire (United Kingdom)',
	215: 'Order of the Crown (Belgium)',
	216: 'Order of the Crown of Thailand',
	217: 'Order of the Date Palm (Iraq)',
	218: 'Order of the Rising Sun (Japan)',
	219: 'Order of the Southern Cross (Brazil)',
	220: 'Order of the White Eagle (Poland)',
	221: 'Order of the White Eagle (Yugoslavia)',
	222: 'Order of Virtuti Militari (Poland)',
	223: 'Order of William (Netherlands)',
	224: 'Outstanding Airman of the Year Ribbon',
	225: 'Outstanding Volunteer Service Medal',
	226: 'Peary Polar Expedition Medal',
	227: 'Philipine Campaign Medal',
	228: 'Philipine Congressional Medal',
	229: 'Philipine Defense Medal',
	230: 'Philipine Independence Medal',
	231: 'Philipine Liberation Medal',
	232: 'Philipine Presidential Unit Citation',
	233: 'Prisoner of War Medal',
	234: 'Purple Heart',
	235: 'Remote Combat Effects Campaign Medal',
	236: 'Republic of Korea Presidential Unit Citation',
	237: 'Republic of Korea War Service Medal',
	238: 'Reserve Special Commendation Ribbon',
	239: 'RVN Air Force Distinguished Service Order',
	240: 'RVN Air Gallantry Cross',
	241: 'RVN Armed Forces Honor Medal',
	242: 'RVN Army Distinguished Service Order',
	243: 'RVN Campaign Medal with 1960- device',
	244: 'RVN Civil Actions Medal (1st Class)',
	245: 'RVN Civil Actions Medal Unit Citation with Pam and Frame (1st Class)',
	246: 'RVN Gallantry Cross (with Palm)',
	247: 'RVN Gallantry Cross Unit Citation with Palm and Frame',
	248: 'RVN Military Merit Medal',
	249: 'RVN Navy Distinguished Service Order',
	250: 'RVN Navy Gallantry Cross',
	251: 'RVN Presidential Unit Citation',
	252: 'RVN Special Service Medal',
	253: 'RVN Staff Service Medal',
	254: 'RVN Training Service Medal',
	255: 'Second Byrd Antarctic Expedition Medal',
	256: 'Secretary of Transportation Outstanding Unit Award',
	257: 'Selected Marine Corps Reserve Medal',
	258: 'Silver Star Medal',
	259: 'Soldierâ€™s Medal',
	260: 'Southwest Asia Service Medal',
	261: 'Spanish Campaign Medal',
	262: 'Spanish War Service Medal',
	263: 'Specially Meritorious Service Medal',
	264: 'Transportation Distinguished Service Medal',
	265: 'United Nations Medal',
	266: 'United Nations Service Medal',
	267: 'United States Antarctic Expedition Medal',
	268: 'Vietnam Service Medal',
	269: 'West Indies Campaign Medal',
	270: 'West Indies Naval Campaign Medal (Sampson Medal)',
	271: 'Women\'s Army Corps Service Medal',
	272: 'World War I Victory Medal',
	273: 'World War II Victory Medal',
	274: 'Yangtze Service Medal'
}

module.exports = { State, DeathCause, SeparationType, BurialPlace, Relationship, ServiceBranch, RankByBranch, Badges}